# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mldev < Formula
  desc "Tools for Mosaic Learning developers and engineers."
  homepage "https://mosaiclearning.com/"
  version "0.4.0"

  depends_on "git"
  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.4.0/mldev_Darwin_arm64.tar.gz"
      sha256 "8b98c963058083be650f0643bc1e84b48fa1137cd53f1b8ec7ff9c3e57868b4c"

      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.4.0/mldev_Darwin_x86_64.tar.gz"
      sha256 "6a46245ed1e2c9451106ecda1ce86c5286b7428be49e73c4eceb8abad69a7898"

      def install
        bin.install "mldev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.4.0/mldev_Linux_arm64.tar.gz"
      sha256 "affb0ae9b2b7fb9cda38fe155140df486e24bf8afacd3bde85e3c02496abdeec"

      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.4.0/mldev_Linux_x86_64.tar.gz"
      sha256 "b172b0e0bcb288d232e9124b6330de82e68cbd5c9a1645758fc64ef6734510e0"

      def install
        bin.install "mldev"
      end
    end
  end
end
