# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mldev < Formula
  desc "Tools for Mosaic Learning developers and engineers."
  homepage "https://mosaiclearning.com/"
  version "0.13.8"

  depends_on "git"
  depends_on "mkcert"
  depends_on "nss"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.13.8/mldev_Darwin_x86_64.tar.gz"
      sha256 "91009128a0964d4dee0b12ce2e1625d768a981b8af063413124ea67b79a8ddbc"

      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.13.8/mldev_Darwin_arm64.tar.gz"
      sha256 "287c848efd25d05037dcf9c00eb71cad0bc86b2f30998bb2476da709b1c12d78"

      def install
        bin.install "mldev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.13.8/mldev_Linux_x86_64.tar.gz"
      sha256 "121af2aaf36e3453a8885e4c038da408d36fe4e83b7529c5efdf4057019c2084"
      def install
        bin.install "mldev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ml-software-services/homebrew-tools/releases/download/v0.13.8/mldev_Linux_arm64.tar.gz"
      sha256 "543a41eb3797f46f0f815999acf4f0d5a857d023a285108ef923f623fc29a78f"
      def install
        bin.install "mldev"
      end
    end
  end
end
